/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyEncrypt */

#ifndef _Included_MyEncrypt
#define _Included_MyEncrypt
#ifdef __cplusplus
extern "C" {
#endif
#undef MyEncrypt_MIN_PRIORITY
#define MyEncrypt_MIN_PRIORITY 1L
#undef MyEncrypt_NORM_PRIORITY
#define MyEncrypt_NORM_PRIORITY 5L
#undef MyEncrypt_MAX_PRIORITY
#define MyEncrypt_MAX_PRIORITY 10L
/*
 * Class:     MyEncrypt
 * Method:    encrypt
 * Signature: ([ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyEncrypt_encrypt
  (JNIEnv *, jobject, jintArray, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
