/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyEncrypt */

#ifndef _Included_MyEncrypt
#define _Included_MyEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyEncrypt
 * Method:    encrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_MyEncrypt_encrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
