/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyDecrypt */

#ifndef _Included_MyDecrypt
#define _Included_MyDecrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyDecrypt
 * Method:    decrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_MyDecrypt_decrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
